plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'org.jetbrains.kotlin.jvm'
}


dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"
//    modImplementation fileTree(dir: "../depend", includes: ["CooParticlesAPI-Fabric-1.21.1-2.1.0.jar"])
    modImplementation "cn.coostack:cooparticlesapi-fabric:${rootProject.coo_particles_api_version}"
//    modImplementation project(':common')
}

fabricApi {
    configureDataGeneration {
        it.client = true
    }
}
tasks.javadoc {
    // fuck javadoc encode error
    enabled = false
}
tasks.named('remapJar') {
    destinationDirectory.set(file("../builds/jar")) // 输出到 build/customLibs
    archiveFileName.set("${rootProject.mod_name}-Fabric-${rootProject.minecraft_version}-${rootProject.version}.jar")
}
loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}